AllCops:
  Exclude:
    - 'spec/**/*'
    - 'bin/**/*'

# Metrics

Metrics/LineLength:
  Max: 120

# Layout

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Style

Style/DoubleNegation:
  Enabled: false
